# Lifted almost directly from:
# https://devices.esphome.io/devices/Wyze-Outdoor-Plug
#
# Build for:
#  board: esp-wrover-kit
# Use the labled pads on the board to flash

substitutions:
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "722"

switch:
  - platform: gpio
    name: Relay 1
    pin:
      number: GPIO15
      inverted: false
      ignore_strapping_warning: true
    id: relay1
    on_turn_on:
      - light.turn_on: relay1_led
    on_turn_off:
      - light.turn_off: relay1_led
  - platform: gpio
    name: Relay 2
    pin:
      number: GPIO32
      inverted: false
    id: relay2
    on_turn_on:
      - light.turn_on: relay2_led
    on_turn_off:
      - light.turn_off: relay2_led

output:
  - platform: gpio
    id: relay1_led_gpio
    pin:
      number: GPIO19
      inverted: true
  - platform: gpio
    id: relay2_led_gpio
    pin:
      number: GPIO16
      inverted: true

light:
  - platform: binary
    id: relay1_led
    name: "Relay 1 LED"
    internal: true
    output: relay1_led_gpio
  - platform: binary
    id: relay2_led
    name: "Relay 2 LED"
    internal: true
    output: relay2_led_gpio

sensor:
  - platform: adc
    id: lux_sensor
    pin: GPIO34
    name: "Lux"
    device_class: illuminance
    unit_of_measurement: lx
    attenuation: 12db
  - platform: hlw8012
    sel_pin:
      number: GPIO25
      inverted: true
    cf_pin: GPIO27
    cf1_pin: GPIO26
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    change_mode_every: 3
    update_interval: 3s
    current:
      name: "Amps"
      unit_of_measurement: A
      accuracy_decimals: 2
    voltage:
      name: "Volts"
      unit_of_measurement: V
      accuracy_decimals: 1
    energy:
      name: "Energy"
    power:
      name: "Watts"
      unit_of_measurement: W
      accuracy_decimals: 0
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 134 -> 58

binary_sensor:
  - platform: gpio
    name: Button 1
    pin:
      number: GPIO18
      mode: INPUT_PULLDOWN
      inverted: false
    on_press:
      - switch.toggle: relay1
  - platform: gpio
    name: Button 2
    pin:
      number: GPIO17
      mode: INPUT_PULLDOWN
      inverted: false
    on_press:
      - switch.toggle: relay2
  - platform: template
    name: Daylight
    device_class: light
    lambda: |-
        // the senor reads 3.1 volts if there is light and 0.5 if there is not light not much inbetween
        if (id(lux_sensor).state > 2) {
          // there is daylight outside.
          return true;
        } else {
          // there is no daylight outside (e.g. it is dark).
          return false;
        }

status_led:
  pin:
    number: GPIO05
    inverted: true
    ignore_strapping_warning: true
