substitutions:
  name: esp32-ble-front
  friendly_name: BLE - Front
  api_key: !secret api-ble-proxy-front
  ota_key: !secret ota-ble-proxy-front

packages:
  ble: !include zi3-ble-gateway.yaml
  base: !include zi3-base.yaml
  board: !include zi3-board-eth.yaml

# BLE Tracker
esp32_ble_tracker:

# Presense sense?
#binary_sensor:
#  - platform: ble_presence
#    service_uuid: !secret ble_token_1
#    name: "Token 1"
#    timeout: 60s
