substitutions:
  name: esp32-bt-zwave
  friendly_name: BT - ZWave
  api_key: !secret api-bt-zwave
  ota_key: !secret ota-bt-zwave

  # USB Z-Wave device
  zwave_vid: 0x303A
  zwave_pid: 0x4001

packages:
  bt: !include zi3-bt.yaml
  base: !include zi3-base.yaml
  board: !include zi3-board-eth.yaml

mdns:
  services:
    - service: "_zwave"
      protocol: "_tcp"
      port: 6053
      txt:
        protocol: "esphome"

logger:
  # ZWave uses USB so log to UART0
  hardware_uart: UART0

usb_host:
  devices:
    - id: usb_zwave
      vid: ${zwave_vid}
      pid: ${zwave_pid}

usb_uart:
  - type: CDC_ACM
    vid: ${zwave_vid}
    pid: ${zwave_pid}
    channels:
      - id: uch_1
        baud_rate: 115200
        buffer_size: 1024

zwave_proxy:
  id: zw_proxy
