esphome:
  name: "cbu-ap-test"
bk72xx:
  board: cbu
wifi:
  #ssid: "no_such_network"
  #password: "1111-2222-3333-4444"
  ap:
    ssid: "cbu-ap-test"
    password: "1111-2222-3333-4444"
captive_portal:
# Conflicting hardware on uart1
logger:
  hardware_uart: uart2

substitutions:
  name: cbu-outlet-office-bench
  friendly_name: Outlet - Office - Bench
  api_key: !secret api-outlet-office-bench
  ota_key: !secret ota-outlet-office-bench
  ap_key: !secret ap-outlet-office-bench
  wifi_ssid: "disable"
  ap_timeout: 15s

  # Device-specifc sensor calibration
  voltage_reference: 15840
  current_reference: 258900
  
  # Guest room defaults to ON but with no local control
  relay1_boot_restore: RESTORE_DEFAULT_ON
  relay2_boot_restore: RESTORE_DEFAULT_ON
  local_restore: RESTORE_DEFAULT_OFF

#packages:
#  ap: !include zi3-ap.yaml
#  base: !include zi3-base.yaml
#  outlet: !include zi3-outlet-elegrp.yaml
