substitutions:
  name: esp32-fan-guest
  friendly_name: "Fan - Guest"
  api_key: !secret api-fan-guest
  ota_key: !secret ota-fan-guest
  ap_key: !secret ap-fan-guest

packages:
  ap: !include zi3-ap.yaml
  base: !include zi3-base.yaml
  fan: !include zi3-fan-transom.yaml