substitutions:
  name: esp32-light-guest-rgb
  friendly_name: Light - Guest - RGB
  api_key: !secret api-light-guest-rgb
  ota_key: !secret ota-light-guest-rgb
  ap_key: !secret ap-light-guest-rgb

  # Lamp minimums in float-percent
  red_min: 0.003262
  blue_min: 0.002738
  green_min: 0.002738

  # Name and icons for HA
  rgb_name: "RGB"
  rgb_icon: mdi:lava-lamp
  frequency_name: "Frequency"
  frequency_icon: mdi:sine-wave

packages:
  ap: !include zi3-ap.yaml
  base: !include zi3-base.yaml
  board: !include zi3-board-c3-zero.yaml

esphome:
  on_boot:
  # RGB to amber @ early boot
  - priority: 600
    then:
      - light.turn_on:
          id: light_rgb
          brightness: 15%
          red: 50%
          blue: 0%
          green: 25%
          transition_length: 1s
  # RGB to 100% (and trigger on_turn_on) @ boot complete
  #- priority: -100
  #  then:
  #    - light.turn_on:
  #        id: light_rgb
  #        brightness: 100%

remote_receiver:
  # 433MHz RF
  pin:
    number: GPIO07
    inverted: True
    mode: INPUT_PULLUP
  filter: 200us
  tolerance: 50%
  idle: 4ms
  dump: rc_switch

output:
  # Red PWM & scaler
  - platform: ledc
    id: led_red
    pin: GPIO20
  - platform: template
    type: float
    id: lamp_red
    write_action: 
      then:
        - output.set_level:
            id: led_red
            level: !lambda |-
              float k = (1.0f - ${red_min}f) / 0.99f;
              return (state > 0.0f) ? (k * state) + ${red_min} : 0.0f;

  # Blue PWM & scaler
  - platform: ledc
    id: led_blue
    pin: GPIO19
  - platform: template
    type: float
    id: lamp_blue
    write_action: 
      then:
        - output.set_level:
            id: led_blue
            level: !lambda |-
              float k = (1.0f - ${blue_min}f) / 0.99f;
              return (state > 0.0f) ? (k * state) + ${blue_min} : 0.0f;

  # Green PWM & scaler
  - platform: ledc
    id: led_green
    pin: GPIO21
  - platform: template
    type: float
    id: lamp_green
    write_action: 
      then:
        - output.set_level:
            id: led_green
            level: !lambda |-
              float k = ((1.0f - ${green_min}f) / 0.99f);
              return (state > 0.0f) ? (k * state) + ${green_min} : 0.0f;

light:
  # Main RGB light
  - platform: rgb
    id: light_rgb
    name: ${rgb_name}
    icon: ${rgb_icon}
    red: lamp_red
    green: lamp_green
    blue: lamp_blue
    restore_mode: ALWAYS_OFF
    default_transition_length: 500ms
    effects:
      - random:
          transition_length: 5s
          update_interval: 7s
      - pulse:
      - strobe:
      - flicker:
    on_turn_on:
      then:
        - light.control:
            id: light_rgb
            effect: random
