substitutions:
  name: esp32-light-bed
  friendly_name: Light - Bed
  api_key: !secret api-light-bed
  ota_key: !secret ota-light-bed
  ap_key: !secret ap-light-bed
  builtin_rgb_name: "Nightlight"
  builtin_rgb_icon: mdi:lightbulb-night

packages:
  ap: !include zi3-ap.yaml
  base: !include zi3-base.yaml
  board: !include zi3-board-s3-zero.yaml

globals:
  - id: last_effect
    type: std::string

esphome:
  on_boot:
    # Lamp 10% flicker @ early boot
    - priority: 600
      then:
      - light.control:
          id: lamp
          state: ON
          brightness: 10%
          effect: flicker
    # Lamp OFF, RGB 20% @ boot complete
    - priority: -100
      then:
      - light.turn_on:
          id: lamp
          brightness: 100%
          transition_length: 10s
      - light.turn_off:
          id: lamp
          transition_length: 0s
      - light.turn_on:
          id: builtin_rgb
          brightness: 20%
          transition_length: 1s

esp32_touch:
  #setup_mode: true
  measurement_duration: 250us
  sleep_duration: 1ms

output:
  - platform: ledc
    id: lamp_led
    pin:
      number: GPIO01

light:
  # Override internal RGB to always be random
  - platform: esp32_rmt_led_strip
    id: !extend builtin_rgb
    default_transition_length: 333ms
    on_turn_on:
      then:
        - light.control:
            id: builtin_rgb
            effect: random
  # Main lamp
  - platform: monochromatic
    id: lamp
    name: Lamp
    icon: mdi:spotlight-beam
    output: lamp_led
    restore_mode: ALWAYS_OFF
    default_transition_length: 333ms
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:

binary_sensor:
  - platform: esp32_touch
    id: touch
    name: Touch
    icon: mdi:gesture-tap
    pin: GPIO02
    threshold: 10000
    on_multi_click:
    # Toggle on tap
    - timing:
        - ON for at most 500ms
        - OFF for at least 50ms
      then:
        - logger.log: "Touch - Toggle"
        - light.toggle: lamp
    # Full brightness on long press
    - timing:
        - ON for 500ms to 1000ms
        - OFF for at least 50ms
      then:
        - logger.log: "Touch - Bright"
        - light.control:
            id: lamp
            state: ON
            brightness: 100%
    # Dim on hold
    - timing:
        - ON for at least 1000ms
      then:
        - logger.log: "Touch - Dim"
        # Disable current effect for better feedback while dimming
        - globals.set:
            id: last_effect
            value: !lambda return id(lamp).get_effect_name();
        - light.control:
            id: lamp
            effect: none
        # Dim 1% every 0.1 seconds
        # Turn full-off and reset brightness to 100% if dimmed below 1%
        - while:
            condition:
              - binary_sensor.is_on: touch
            then:
              - light.dim_relative:
                  id: lamp
                  relative_brightness: -1%
                  transition_length: 0.1s
              - delay: 0.1s
        # Restore previous effect
        - light.control:
            id: lamp
            effect: !lambda return id(last_effect);
