substitutions:
  name: cbu-outlet-guest-vanity
  friendly_name: Outlet - Guest - Vanity
  api_key: !secret api-outlet-guest-vanity
  ota_key: !secret ota-outlet-guest-vanity
  ap_key: !secret ap-outlet-guest-vanity

  # Device-specifc sensor calibration
  voltage_reference: 15930
  current_reference: 253390

  # Guest room defaults to ON but with no local control
  relay1_boot_restore: RESTORE_DEFAULT_ON
  relay2_boot_restore: RESTORE_DEFAULT_ON
  local_restore: RESTORE_DEFAULT_OFF

packages:
  # AP usually fails on this board, but maybe future versions will work
  #ap: !include zi3-ap.yaml
  base: !include zi3-base.yaml
  outlet: !include zi3-outlet-elegrp.yaml
