substitutions:
  name: cbu-outlet-guest-closet
  friendly_name: Outlet - Guest - Closet
  api_key: !secret api-outlet-guest-closet
  ota_key: !secret ota-outlet-guest-closet
  ap_key: !secret ap-outlet-guest-closet

  # Device-specifc sensor calibration
  voltage_reference: 15840
  current_reference: 258900
  
  # Guest room defaults to ON but with no local control
  relay1_boot_restore: RESTORE_DEFAULT_ON
  relay2_boot_restore: RESTORE_DEFAULT_ON
  local_restore: RESTORE_DEFAULT_OFF

  # Reduce the default limit for this old box
  current_limit_default: "8.0"

packages:
  # AP usually fails on this board, but maybe future versions will work
  #ap: !include zi3-ap.yaml
  base: !include zi3-base.yaml
  outlet: !include zi3-outlet-elegrp.yaml
