substitutions:
  name: esp32-seeed-epaper
  friendly_name: "ePaper - Buttons"
  api_key: !secret api-seeed-epaper
  ota_key: !secret ota-seeed-epaper
  ap_key: !secret ap-seeed-epaper

  font_size: 80
  font2_size: 40
  qr_scale: 4
  tab_size: ${font2_size}
  #door_code: "7738"
  #wifi_passwd: "tocsin-clammy-marae"

packages:
  base: !include zi3-base.yaml
  board: !include zi3-board-epaper.yaml

api:
  on_client_connected:
    - delay: 500ms
    - component.update: big_display

binary_sensor:
  - id: !extend button_1
    on_press:
      then:
        - component.update: big_display

button:
  - platform: template
    id: screen_update
    name: "Force Update"
    on_press:
      then:
        - component.update: big_display

font:
  - file: "Roboto-Regular.ttf"
    id: roboto
    size: ${font_size}
  - file: "Roboto-Regular.ttf"
    id: roboto2
    size: ${font2_size}

# Data from HA
text_sensor:
  - platform: homeassistant
    entity_id: sensor.guest_door
    id: ha_door
    attribute: "code"
  - platform: homeassistant
    entity_id: sensor.guest_wifi
    id: ha_wifi_name
    attribute: "name"
  - platform: homeassistant
    entity_id: sensor.guest_wifi
    id: ha_wifi_key
    attribute: "key"

qr_code:
  - id: wifi_qr
    value: ""

display:
  - platform: waveshare_epaper
    id: big_display
    # 640x480 B/W (Inverted Busy)
    model: 5.83inv2
    cs_pin: GPIO44
    dc_pin: GPIO10
    reset_pin: GPIO38
    busy_pin:
      number: GPIO4
      inverted: True
    update_interval: never
    rotation: 180
    lambda: |-
      Color black = Color(255,255,255);
      id(wifi_qr).set_value(
        (std::string)"WIFI:S:" +
        id(ha_wifi_name).state +
        (std::string)";T:WPA;P:" +
        id(ha_wifi_key).state +
        (std::string)";;");

      int i = 0;
      it.printf(it.get_width() / 2, i, id(roboto), TextAlign::TOP_CENTER, "Peter");
      i += ${font_size};

      i += ${font2_size};
      it.printf(0, i, id(roboto2), "Arrival:");
      it.printf(it.get_width(), i, id(roboto2), TextAlign::TOP_RIGHT, "2026-05-21 @   2 PM");
      i += ${font2_size};
      it.printf(0, i, id(roboto2), "Departure:");
      it.printf(it.get_width(), i, id(roboto2), TextAlign::TOP_RIGHT, "2026-05-22 @ 12 PM");
      i += ${font2_size};

      i += ${font2_size};
      it.printf(0, i, id(roboto2), "Door Code: %s", id(ha_door).state);

      i += ${font2_size};
      i += ${font2_size};
      int q_bottom = i + (id(wifi_qr).get_size() * ${qr_scale});
      it.qr_code((it.get_width() - (id(wifi_qr).get_size() * ${qr_scale})) - ${tab_size}, i, id(wifi_qr), black, ${qr_scale});
      it.printf(0, i, id(roboto2), "WiFi: %s", id(ha_wifi_name).state);
      i += ${font2_size};
      it.printf(${tab_size}, i, id(roboto2), "%s", id(ha_wifi_key).state);
