substitutions:
  name: esp32-sensor-couch
  friendly_name: "Sensor - Couch"
  api_key: !secret api-sensor-couch
  ota_key: !secret ota-sensor-couch
  ap_key: !secret ap-sensor-couch

  # BME280 power via GPIO
  pin_power_vcc: GPIO47
  pin_power_gnd: GPIO38
  pin_power_name: "BME280 Power"
  pin_power_icon: mdi:toggle-switch
  pin_power_prefix: "bme280_"

packages:
  nvm: !include zi3-nvm.yaml
  base: !include zi3-base.yaml
  board: !include zi3-board-s3-nano.yaml
  bme280: !include zi3-bme280.yaml
  pinpower: !include zi3-pinpower.yaml

i2c:
  - id: i2c_bme280
    sda: GPIO18
    scl: GPIO21
