substitutions:
  name: esp8285-sensor-433mhz
  friendly_name: "Sensor - 433MHz"
  api_key: !secret api-sensor-433mhz
  ota_key: !secret ota-sensor-433mhz
  ap_key: !secret ap-sensor-433mhz

packages:
  base: !include zi3-base.yaml
  board: !include zi3-board-esp8285.yaml
  rf_doors: !include zi3-rf-door-sensor.yaml

# Radio RX
remote_receiver:
  pin: GPIO04
  filter: 200us
  tolerance: 50%
  idle: 4ms
  dump: rc_switch

# Radio TX
remote_transmitter:
  pin: GPIO05
  carrier_duty_percent: 100%

# Status LED
status_led:
  pin: {number: GPIO13, inverted: True}

# Logo LED (green)
output:
  - platform: esp8266_pwm
    id: logo_output
    pin: GPIO12
light:
  - platform: monochromatic
    output: logo_output
    name: "Logo LED"
