# Pinout source: https://wiki.seeedstudio.com/xiao_esp32s3_getting_started/

substitutions:
  xiao_board: esp32-s3-devkitc-1
  xiao_flash_size: 8MB
  builtin_mono_name: "Builtin Mono"
  builtin_mono_icon: mdi:head-lightbulb-outline

packages:
  esp32: !include zi3-board-esp32.yaml
  wifi: !include zi3-wifi.yaml

esp32:
  board: ${xiao_board}
  flash_size: ${xiao_flash_size}

esphome:
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio

output:
  - platform: ledc
    id: user_led
    pin:
      number: GPIO21
      inverted: true

light:
  - platform: monochromatic
    id: builtin_mono
    name: ${builtin_mono_name}
    icon: ${builtin_mono_icon}
    output: user_led
