# Pinout source: https://www.waveshare.com/wiki/ESP32-S3-Nano

substitutions:
  nano_board: esp32-s3-devkitc-1
  nano_flash_size: 16MB
  builtin_rgb_name: "Builtin RGB"
  builtin_rgb_icon: mdi:head-lightbulb-outline
  builtin_rgb_internal: False
  builtin_mono_name: "Builtin Mono"
  builtin_mono_icon: mdi:head-lightbulb-outline
  builtin_mono_internal: ${builtin_rgb_internal}

  # Lamp constants
  builtin_mono_min: 0.01
  builtin_red_min: 0.01
  builtin_green_min: 0.01
  builtin_blue_min: 0.01

packages:
  esp32: !include zi3-board-esp32.yaml
  wifi: !include zi3-wifi.yaml

esp32:
  board: ${nano_board}
  flash_size: ${nano_flash_size}

psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: False

light:
  - platform: rgb
    id: builtin_rgb
    name: ${builtin_rgb_name}
    icon: ${builtin_rgb_icon}
    internal: ${builtin_rgb_internal}
    red: builtin_red_lamp
    green: builtin_green_lamp
    blue: builtin_blue_lamp
  - platform: monochromatic
    id: builtin_mono
    name: ${builtin_mono_name}
    icon: ${builtin_mono_icon}
    internal: ${builtin_mono_internal}
    output: builtin_mono_lamp

output:
  - platform: ledc
    id: builtin_mono_lamp
    # This is also the SCK line
    pin: GPIO48
    min_power: ${builtin_mono_min}
    zero_means_zero: True

  - platform: ledc
    id: builtin_blue_lamp
    pin:
      number: GPIO45
      ignore_strapping_warning: True
    inverted: True
    min_power: ${builtin_blue_min}
    zero_means_zero: True

  - platform: ledc
    id: builtin_red_lamp
    pin:
      number: GPIO46
      ignore_strapping_warning: True
    inverted: True
    min_power: ${builtin_red_min}
    zero_means_zero: True

  - platform: ledc
    id: builtin_green_lamp
    pin:
      number: GPIO0
      ignore_strapping_warning: True
    inverted: True
    min_power: ${builtin_green_min}
    zero_means_zero: True

# Pin map
# D13: GPIO48 (SCK)
# B0: GPIO46
# A0: GPIO01
# A1: GPIO02
# A2: GPIO03
# A3: GPIO04
# A4: GPIO11 (SDA)
# A5: GPIO12 (SCL)
# A6: GPIO13
# A7: GPIO14
# B1: GPIO00
# D12: GPIO47 (MISO)
# D11: GPIO38 (MOSI)
# D10: GPIO21
# D9: GPIO18
# D8: GPIO17
# D7: GPIO10
# D6: GPIO09
# D5: GPIO08
# D4: GPIO07
# D3: GPIO06
# D2: GPIO05
# RX0: GPIO44
# TX1: GPIO43