substitutions:
  esp8285_board: esp8285
  restore_from_flash: False

esp8266:
  board: ${esp8285_board}

  # ESP2666 doesn't have preference NVM, but can restore from flash
  # Off by default. Enable if you include zi3-nvm.yaml
  restore_from_flash: ${restore_from_flash}

packages:
  wifi: !include zi3-wifi.yaml
