substitutions:
  esp32_framework_type: esp-idf
  internal_temp_name: 'Internal Temperature'
  internal_temp_icon: mdi:oil-temperature
  internal_temp_interval: 300s
  restart_name: 'Restart device'
  restart_icon: mdi:reload

esp32:
  framework:
    type: ${esp32_framework_type}

sensor:
  - platform: internal_temperature
    id: system_internal_temperature
    name: ${internal_temp_name}
    icon: ${internal_temp_icon}
    update_interval: ${internal_temp_interval}
    entity_category: diagnostic
    device_class: temperature
    unit_of_measurement: "°C"
    disabled_by_default: True

button:
  - platform: restart
    id: system_restart
    name: ${restart_name}
    icon: ${restart_icon}
    entity_category: config
    disabled_by_default: True
