substitutions:
  bk72xx_board: cbu
  temperature_name: 'Internal Temperature'
  temperature_icon: mdi:oil-temperature
  temperature_interval: 300s
  restart_name: 'Restart device'
  restart_icon: mdi:reload

packages:
  wifi: !include zi3-wifi.yaml

bk72xx:
  board: ${bk72xx_board}

sensor:
  - platform: internal_temperature
    id: system_internal_temperature
    name: ${temperature_name}
    icon: ${temperature_icon}
    update_interval: ${temperature_interval}
    entity_category: diagnostic
    device_class: "temperature"
    unit_of_measurement: "°C"
    disabled_by_default: True

button:
  - platform: restart
    id: system_restart
    name: ${restart_name}
    icon: ${restart_icon}
    entity_category: config
    disabled_by_default: True
