substitutions:
  enable_ipv6: true
  wifi_power_save: LIGHT
  wifi_ssid: !secret wifi_ssid
  wifi_key: !secret wifi_password
  wifi_ip_interval: 1h
  wifi_signal_interval: ${wifi_ip_interval}
  wifi_bssid_interval: ${wifi_ip_interval}
  wifi_ssid_interval: ${wifi_ip_interval}
  wifi_scan_interval: never

network:
    enable_ipv6: ${enable_ipv6}

wifi:
  power_save_mode: ${wifi_power_save}
  ssid: ${wifi_ssid}
  password: ${wifi_key}

sensor:
  # WiFi strength in dB
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    entity_category: diagnostic
    update_interval: ${wifi_signal_interval}
    disabled_by_default: True
  # WiFi stength in percent
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal %"
    filters:
      - lambda: return min(max(2.06 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
    device_class: ""
    disabled_by_default: True

text_sensor:
  - platform: wifi_info
    ip_address:
      name: Device IP
      icon: mdi:ip-network
      entity_category: diagnostic
      update_interval: ${wifi_ip_interval}
      disabled_by_default: True
    mac_address:
      name: Device MAC
      icon: mdi:chip
      entity_category: diagnostic
      disabled_by_default: True
    ssid:
      name: Device SSID
      icon: mdi:chip
      entity_category: diagnostic
      update_interval: ${wifi_ssid_interval}
      disabled_by_default: True
    bssid:
      name: Device BSSID
      icon: mdi:chip
      entity_category: diagnostic
      update_interval: ${wifi_bssid_interval}
      disabled_by_default: True
    scan_results:
      name: WiFi Scan
      icon: mdi:chip
      entity_category: diagnostic
      update_interval: ${wifi_scan_interval}
      disabled_by_default: True
