network:
    enable_ipv6: true

wifi:
  power_save_mode: NONE
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    entity_category: "diagnostic"
    update_interval: 300s
    disabled_by_default: true
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal %"
    filters:
      - lambda: return min(max(2.06 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""
    disabled_by_default: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: Device IP
      icon: mdi:ip-network
      entity_category: diagnostic
      update_interval: 300s
      disabled_by_default: true
    mac_address:
      name: Device MAC
      icon: mdi:chip
      entity_category: diagnostic
      disabled_by_default: true
    ssid:
      name: Device SSID
      icon: mdi:chip
      entity_category: diagnostic
      update_interval: never
      disabled_by_default: true
    bssid:
      name: Device BSSID
      icon: mdi:chip
      entity_category: diagnostic
      update_interval: 300s
      disabled_by_default: true
    scan_results:
      name: WiFi Scan
      icon: mdi:chip
      entity_category: diagnostic
      update_interval: never
      disabled_by_default: true
