# https://www.waveshare.com/wiki/ESP32-C3-Zero

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

light:
  - platform: esp32_rmt_led_strip
    name: "Builtin RBG"
    pin:
      number: GPIO10
    chipset: WS2812
    rgb_order: RGB
    num_leds: 1
    disabled_by_default: true

sensor:
  - platform: internal_temperature
    id: system_internal_temperature
    name: Internal Temperature
    icon: mdi:oil-temperature
    update_interval: 300s
    entity_category: diagnostic
    device_class: "temperature"
    unit_of_measurement: "°C"
    disabled_by_default: true

button:
  - platform: restart
    id: system_restart
    name: Restart device
    icon: mdi:reload
    entity_category: config
    disabled_by_default: true
