substitutions:
  esp32_framework_type: esp-idf

esp32:
  framework:
    type: ${esp32_framework_type}

sensor:
  - platform: internal_temperature
    id: system_internal_temperature
    name: Internal Temperature
    icon: mdi:oil-temperature
    update_interval: 300s
    entity_category: diagnostic
    device_class: "temperature"
    unit_of_measurement: "°C"
    disabled_by_default: true

button:
  - platform: restart
    id: system_restart
    name: Restart device
    icon: mdi:reload
    entity_category: config
    disabled_by_default: true
