# Pinout source: https://learn.adafruit.com/adafruit-esp32-feather-v2/pinouts

substitutions:
  builtin_mono_name: "Builtin Mono"
  builtin_mono_icon: mdi:head-lightbulb-outline
  builtin_rgb_name: "Builtin RGB"
  builtin_rgb_icon: mdi:head-lightbulb-outline
  builtin_rgb_power_name: "${builtin_rgb_name} Enable"
  builtin_rgb_power_icon: mdi:toggle-switch

esp32:
  board: adafruit_feather_esp32_v2

packages:
  esp32: !include esp32.yaml

#spi:
#  clk_pin: GPIO36
#  mosi_pin: GPIO35
#  miso_pin: GPIO37
#  interface: hardware

#i2c:
#  sda: GPIO3
#  scl: GPIO4

switch:
  - platform: gpio
    id: builtin_rgb_power
    name: ${builtin_rgb_power_name}
    icon: ${builtin_rgb_power_icon}
    restore_mode: ALWAYS_ON
    entity_category: config
    pin:
      number: GPIO2
      ignore_strapping_warning: true

output:
  - platform: ledc
    id: builtin_red
    pin: GPIO13

light:
  - platform: monochromatic
    output: builtin_red
    id: builtin_mono
    name: ${builtin_mono_name}
    icon: ${builtin_mono_icon}
  - platform: esp32_rmt_led_strip
    id: builtin_rgb
    name: ${builtin_rgb_name}
    icon: ${builtin_rgb_icon}
    pin:
      number: GPIO0
      ignore_strapping_warning: true
    chipset: WS2812
    rgb_order: GRB
    num_leds: 1
