# https://www.waveshare.com/wiki/ESP32-S3-ETH

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

light:
  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: GPIO21
    num_leds: 1
    rgb_order: GRB
    name: "Builtin LED"

sensor:
  - platform: internal_temperature
    id: system_internal_temperature
    name: Internal Temperature
    icon: mdi:oil-temperature
    update_interval: 300s
    entity_category: diagnostic
    device_class: "temperature"
    unit_of_measurement: "°C"
    disabled_by_default: true

button:
  - platform: restart
    id: system_restart
    name: Restart device
    icon: mdi:reload
    entity_category: config
    disabled_by_default: true
