esphome:
  name: ${name}
  friendly_name: ${long_name}

logger:

api:
  encryption:
    key: ${api_key}

ota:
  - platform: esphome
    id: self_ota
    password: ${ota_key}

binary_sensor:
  - platform: status
    name: Status

sensor:
  - platform: uptime
    id: system_uptime
    name: Device Uptime
    icon: mdi:power-settings
    update_interval: 300s
    entity_category: diagnostic
    state_class: total_increasing
    disabled_by_default: true

button:
  - platform: safe_mode
    id: system_safe_mode
    name: Enter safe mode
    icon: mdi:alert
    entity_category: config
    disabled_by_default: true
  - platform: shutdown
    id: system_shutdown
    name: Shutdown
    icon: mdi:power
    entity_category: config
    disabled_by_default: true
  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
    entity_category: config
    disabled_by_default: true
